apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep
    - "5000"
    image: busybox:1.28
    name: busybox
    volumeMounts:
      - mountPath: "/my/data"
        name: mydata
    resources: {}
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: redis-data-claim    # example can be found in volume folder
  securityContext:
    runAsUser: 1001  # simulating bitnami apps
    runAsGroup: 1001
    fsGroup: 1001
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
