apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep
    - "5000"
    image: busybox:1.28
    name: busybox
    volumeMounts:
      - mountPath: "/mydata"
        name: mydata
    resources: {}
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: local-path-claim    # example can be found in volume folder
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
