apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/kdata" # Sets the volume's path  - folder should exist on local file-system
