apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/kdata" # Sets the volume's path  - folder should exist on local file-system
