apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Sets volume size
